name: "Closed PR/Issue - Auto Triage"
run-name: Contribution by ${{ github.actor }} - Auto Triage - ${{ github.event.issue.state }}
description:

on:
  pull_request:
    types: [closed, converted_to_draft]
  issues:
    types: [closed]

jobs:
  Triage:
    uses: SessionsBot/.github/.github/workflows/closed-auto-triage.yml@main
    permissions:
      pull-requests: write
      issues: write
