name: Manual Label Sync

on:
    workflow_dispatch:

permissions:
    issues: write
    pull-requests: write

jobs:
    Sync-Labels:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch/update from config
              run: gh label clone SessionsBot/.github --force
