name: Manual Label Sync

on:
    workflow_dispatch:

permissions:
    issues: write
    pull-requests: write

jobs:
    Sync-Labels:
        uses: SessionsBot/.github/.github/workflows/sync-all-labels.yml@main
        permissions:
            pull-requests: write
            issues: write